/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Product
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const findById2 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product>(
      {url: `/products/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById2QueryKey = (id?: string,) => {
    return [
    `/products/${id}`
    ] as const;
    }

    
export const getFindById2QueryOptions = <TData = Awaited<ReturnType<typeof findById2>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById2QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById2>>> = ({ signal }) => findById2(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById2QueryResult = NonNullable<Awaited<ReturnType<typeof findById2>>>
export type FindById2QueryError = unknown


export function useFindById2<TData = Awaited<ReturnType<typeof findById2>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById2>>,
          TError,
          Awaited<ReturnType<typeof findById2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById2<TData = Awaited<ReturnType<typeof findById2>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById2>>,
          TError,
          Awaited<ReturnType<typeof findById2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById2<TData = Awaited<ReturnType<typeof findById2>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById2<TData = Awaited<ReturnType<typeof findById2>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById2>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById2QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const update2 = (
    id: string,
    product: Product,
 ) => {
      
      
      return customInstance<Product>(
      {url: `/products/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: product
    },
      );
    }
  


export const getUpdate2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update2>>, TError,{id: string;data: Product}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof update2>>, TError,{id: string;data: Product}, TContext> => {

const mutationKey = ['update2'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update2>>, {id: string;data: Product}> = (props) => {
          const {id,data} = props ?? {};

          return  update2(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Update2MutationResult = NonNullable<Awaited<ReturnType<typeof update2>>>
    export type Update2MutationBody = Product
    export type Update2MutationError = unknown

    export const useUpdate2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update2>>, TError,{id: string;data: Product}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof update2>>,
        TError,
        {id: string;data: Product},
        TContext
      > => {

      const mutationOptions = getUpdate2MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const delete2 = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/products/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDelete2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete2>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof delete2>>, TError,{id: string}, TContext> => {

const mutationKey = ['delete2'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete2>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  delete2(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete2MutationResult = NonNullable<Awaited<ReturnType<typeof delete2>>>
    
    export type Delete2MutationError = unknown

    export const useDelete2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete2>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete2>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDelete2MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAll2 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product[]>(
      {url: `/products`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll2QueryKey = () => {
    return [
    `/products`
    ] as const;
    }

    
export const getFindAll2QueryOptions = <TData = Awaited<ReturnType<typeof findAll2>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll2QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll2>>> = ({ signal }) => findAll2(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll2QueryResult = NonNullable<Awaited<ReturnType<typeof findAll2>>>
export type FindAll2QueryError = unknown


export function useFindAll2<TData = Awaited<ReturnType<typeof findAll2>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll2>>,
          TError,
          Awaited<ReturnType<typeof findAll2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll2<TData = Awaited<ReturnType<typeof findAll2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll2>>,
          TError,
          Awaited<ReturnType<typeof findAll2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll2<TData = Awaited<ReturnType<typeof findAll2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll2<TData = Awaited<ReturnType<typeof findAll2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll2>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll2QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const create2 = (
    product: Product,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: product, signal
    },
      );
    }
  


export const getCreate2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create2>>, TError,{data: Product}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create2>>, TError,{data: Product}, TContext> => {

const mutationKey = ['create2'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create2>>, {data: Product}> = (props) => {
          const {data} = props ?? {};

          return  create2(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create2MutationResult = NonNullable<Awaited<ReturnType<typeof create2>>>
    export type Create2MutationBody = Product
    export type Create2MutationError = unknown

    export const useCreate2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create2>>, TError,{data: Product}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create2>>,
        TError,
        {data: Product},
        TContext
      > => {

      const mutationOptions = getCreate2MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findByCategory = (
    category: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product[]>(
      {url: `/products/category/${category}`, method: 'GET', signal
    },
      );
    }
  



export const getFindByCategoryQueryKey = (category?: string,) => {
    return [
    `/products/category/${category}`
    ] as const;
    }

    
export const getFindByCategoryQueryOptions = <TData = Awaited<ReturnType<typeof findByCategory>>, TError = unknown>(category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByCategoryQueryKey(category);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findByCategory>>> = ({ signal }) => findByCategory(category, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(category), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindByCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof findByCategory>>>
export type FindByCategoryQueryError = unknown


export function useFindByCategory<TData = Awaited<ReturnType<typeof findByCategory>>, TError = unknown>(
 category: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByCategory>>,
          TError,
          Awaited<ReturnType<typeof findByCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByCategory<TData = Awaited<ReturnType<typeof findByCategory>>, TError = unknown>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByCategory>>,
          TError,
          Awaited<ReturnType<typeof findByCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByCategory<TData = Awaited<ReturnType<typeof findByCategory>>, TError = unknown>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindByCategory<TData = Awaited<ReturnType<typeof findByCategory>>, TError = unknown>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByCategory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindByCategoryQueryOptions(category,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const findActive = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product[]>(
      {url: `/products/active`, method: 'GET', signal
    },
      );
    }
  



export const getFindActiveQueryKey = () => {
    return [
    `/products/active`
    ] as const;
    }

    
export const getFindActiveQueryOptions = <TData = Awaited<ReturnType<typeof findActive>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindActiveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findActive>>> = ({ signal }) => findActive(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindActiveQueryResult = NonNullable<Awaited<ReturnType<typeof findActive>>>
export type FindActiveQueryError = unknown


export function useFindActive<TData = Awaited<ReturnType<typeof findActive>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findActive>>,
          TError,
          Awaited<ReturnType<typeof findActive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindActive<TData = Awaited<ReturnType<typeof findActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findActive>>,
          TError,
          Awaited<ReturnType<typeof findActive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindActive<TData = Awaited<ReturnType<typeof findActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindActive<TData = Awaited<ReturnType<typeof findActive>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findActive>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindActiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



