/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Booking,
  CancelBody
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const findAll5 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking[]>(
      {url: `/bookings`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll5QueryKey = () => {
    return [
    `/bookings`
    ] as const;
    }

    
export const getFindAll5QueryOptions = <TData = Awaited<ReturnType<typeof findAll5>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll5QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll5>>> = ({ signal }) => findAll5(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll5QueryResult = NonNullable<Awaited<ReturnType<typeof findAll5>>>
export type FindAll5QueryError = unknown


export function useFindAll5<TData = Awaited<ReturnType<typeof findAll5>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll5>>,
          TError,
          Awaited<ReturnType<typeof findAll5>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll5<TData = Awaited<ReturnType<typeof findAll5>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll5>>,
          TError,
          Awaited<ReturnType<typeof findAll5>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll5<TData = Awaited<ReturnType<typeof findAll5>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll5<TData = Awaited<ReturnType<typeof findAll5>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll5>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll5QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const create5 = (
    booking: Booking,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking>(
      {url: `/bookings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: booking, signal
    },
      );
    }
  


export const getCreate5MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create5>>, TError,{data: Booking}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create5>>, TError,{data: Booking}, TContext> => {

const mutationKey = ['create5'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create5>>, {data: Booking}> = (props) => {
          const {data} = props ?? {};

          return  create5(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create5MutationResult = NonNullable<Awaited<ReturnType<typeof create5>>>
    export type Create5MutationBody = Booking
    export type Create5MutationError = unknown

    export const useCreate5 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create5>>, TError,{data: Booking}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create5>>,
        TError,
        {data: Booking},
        TContext
      > => {

      const mutationOptions = getCreate5MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const cancel = (
    id: string,
    cancelBody: CancelBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking>(
      {url: `/bookings/${id}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cancelBody, signal
    },
      );
    }
  


export const getCancelMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancel>>, TError,{id: string;data: CancelBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cancel>>, TError,{id: string;data: CancelBody}, TContext> => {

const mutationKey = ['cancel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancel>>, {id: string;data: CancelBody}> = (props) => {
          const {id,data} = props ?? {};

          return  cancel(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelMutationResult = NonNullable<Awaited<ReturnType<typeof cancel>>>
    export type CancelMutationBody = CancelBody
    export type CancelMutationError = unknown

    export const useCancel = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancel>>, TError,{id: string;data: CancelBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancel>>,
        TError,
        {id: string;data: CancelBody},
        TContext
      > => {

      const mutationOptions = getCancelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findById6 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking>(
      {url: `/bookings/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById6QueryKey = (id?: string,) => {
    return [
    `/bookings/${id}`
    ] as const;
    }

    
export const getFindById6QueryOptions = <TData = Awaited<ReturnType<typeof findById6>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById6QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById6>>> = ({ signal }) => findById6(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById6QueryResult = NonNullable<Awaited<ReturnType<typeof findById6>>>
export type FindById6QueryError = unknown


export function useFindById6<TData = Awaited<ReturnType<typeof findById6>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById6>>,
          TError,
          Awaited<ReturnType<typeof findById6>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
  
export function useFindById6<TData = Awaited<ReturnType<typeof findById6>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById6>>,
          TError,
          Awaited<ReturnType<typeof findById6>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById6<TData = Awaited<ReturnType<typeof findById6>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById6<TData = Awaited<ReturnType<typeof findById6>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById6>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById6QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const delete5 = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/bookings/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDelete5MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete5>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof delete5>>, TError,{id: string}, TContext> => {

const mutationKey = ['delete5'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete5>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  delete5(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete5MutationResult = NonNullable<Awaited<ReturnType<typeof delete5>>>
    
    export type Delete5MutationError = unknown

    export const useDelete5 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete5>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete5>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDelete5MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findByStatus2 = (
    status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT',
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking[]>(
      {url: `/bookings/status/${status}`, method: 'GET', signal
    },
      );
    }
  



export const getFindByStatus2QueryKey = (status?: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT',) => {
    return [
    `/bookings/status/${status}`
    ] as const;
    }

export const approve = (
    id: string,
    data?: Record<string, unknown>,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Booking>(
      {url: `/bookings/${id}/approve`, method: 'POST', data, signal
    },
      );
    }
  

export type ApproveVariables = {id: string; data?: Record<string, unknown>}

export const getApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,ApproveVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,ApproveVariables, TContext> => {

const mutationKey = ['approve'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approve>>, ApproveVariables> = (props) => {
          const {id, data} = props ?? {};

          return  approve(id, data,)
        }

        

  return  { mutationFn, ...mutationOptions }}

    export type ApproveMutationResult = NonNullable<Awaited<ReturnType<typeof approve>>>
    
    export type ApproveMutationError = unknown

    export const useApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,ApproveVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approve>>,
        TError,
        ApproveVariables,
        TContext
      > => {

      const mutationOptions = getApproveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getFindByStatus2QueryOptions = <TData = Awaited<ReturnType<typeof findByStatus2>>, TError = unknown>(status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByStatus2QueryKey(status);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findByStatus2>>> = ({ signal }) => findByStatus2(status, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(status), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindByStatus2QueryResult = NonNullable<Awaited<ReturnType<typeof findByStatus2>>>
export type FindByStatus2QueryError = unknown


export function useFindByStatus2<TData = Awaited<ReturnType<typeof findByStatus2>>, TError = unknown>(
 status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus2>>,
          TError,
          Awaited<ReturnType<typeof findByStatus2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus2<TData = Awaited<ReturnType<typeof findByStatus2>>, TError = unknown>(
 status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus2>>,
          TError,
          Awaited<ReturnType<typeof findByStatus2>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus2<TData = Awaited<ReturnType<typeof findByStatus2>>, TError = unknown>(
 status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindByStatus2<TData = Awaited<ReturnType<typeof findByStatus2>>, TError = unknown>(
 status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'CHECKIN' | 'CHECKOUT', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus2>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindByStatus2QueryOptions(status,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



