/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Room
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const findById1 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Room>(
      {url: `/rooms/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById1QueryKey = (id?: string,) => {
    return [
    `/rooms/${id}`
    ] as const;
    }

    
export const getFindById1QueryOptions = <TData = Awaited<ReturnType<typeof findById1>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById1>>> = ({ signal }) => findById1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById1QueryResult = NonNullable<Awaited<ReturnType<typeof findById1>>>
export type FindById1QueryError = unknown


export function useFindById1<TData = Awaited<ReturnType<typeof findById1>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById1>>,
          TError,
          Awaited<ReturnType<typeof findById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById1<TData = Awaited<ReturnType<typeof findById1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById1>>,
          TError,
          Awaited<ReturnType<typeof findById1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById1<TData = Awaited<ReturnType<typeof findById1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById1<TData = Awaited<ReturnType<typeof findById1>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const update1 = (
    id: string,
    room: Room,
 ) => {
      
      
      return customInstance<Room>(
      {url: `/rooms/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: room
    },
      );
    }
  


export const getUpdate1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: string;data: Room}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: string;data: Room}, TContext> => {

const mutationKey = ['update1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update1>>, {id: string;data: Room}> = (props) => {
          const {id,data} = props ?? {};

          return  update1(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Update1MutationResult = NonNullable<Awaited<ReturnType<typeof update1>>>
    export type Update1MutationBody = Room
    export type Update1MutationError = unknown

    export const useUpdate1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update1>>, TError,{id: string;data: Room}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof update1>>,
        TError,
        {id: string;data: Room},
        TContext
      > => {

      const mutationOptions = getUpdate1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const delete1 = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/rooms/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDelete1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: string}, TContext> => {

const mutationKey = ['delete1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  delete1(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete1MutationResult = NonNullable<Awaited<ReturnType<typeof delete1>>>
    
    export type Delete1MutationError = unknown

    export const useDelete1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete1>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete1>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDelete1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAll1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Room[]>(
      {url: `/rooms`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll1QueryKey = () => {
    return [
    `/rooms`
    ] as const;
    }

    
export const getFindAll1QueryOptions = <TData = Awaited<ReturnType<typeof findAll1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll1>>> = ({ signal }) => findAll1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll1QueryResult = NonNullable<Awaited<ReturnType<typeof findAll1>>>
export type FindAll1QueryError = unknown


export function useFindAll1<TData = Awaited<ReturnType<typeof findAll1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll1>>,
          TError,
          Awaited<ReturnType<typeof findAll1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll1<TData = Awaited<ReturnType<typeof findAll1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll1>>,
          TError,
          Awaited<ReturnType<typeof findAll1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll1<TData = Awaited<ReturnType<typeof findAll1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll1<TData = Awaited<ReturnType<typeof findAll1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const create1 = (
    room: Room,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Room>(
      {url: `/rooms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: room, signal
    },
      );
    }
  


export const getCreate1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: Room}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: Room}, TContext> => {

const mutationKey = ['create1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create1>>, {data: Room}> = (props) => {
          const {data} = props ?? {};

          return  create1(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create1MutationResult = NonNullable<Awaited<ReturnType<typeof create1>>>
    export type Create1MutationBody = Room
    export type Create1MutationError = unknown

    export const useCreate1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create1>>, TError,{data: Room}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create1>>,
        TError,
        {data: Room},
        TContext
      > => {

      const mutationOptions = getCreate1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findByStatus1 = (
    status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE',
 signal?: AbortSignal
) => {
      
      
      return customInstance<Room[]>(
      {url: `/rooms/status/${status}`, method: 'GET', signal
    },
      );
    }
  



export const getFindByStatus1QueryKey = (status?: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE',) => {
    return [
    `/rooms/status/${status}`
    ] as const;
    }

    
export const getFindByStatus1QueryOptions = <TData = Awaited<ReturnType<typeof findByStatus1>>, TError = unknown>(status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByStatus1QueryKey(status);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findByStatus1>>> = ({ signal }) => findByStatus1(status, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(status), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindByStatus1QueryResult = NonNullable<Awaited<ReturnType<typeof findByStatus1>>>
export type FindByStatus1QueryError = unknown


export function useFindByStatus1<TData = Awaited<ReturnType<typeof findByStatus1>>, TError = unknown>(
 status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus1>>,
          TError,
          Awaited<ReturnType<typeof findByStatus1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus1<TData = Awaited<ReturnType<typeof findByStatus1>>, TError = unknown>(
 status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus1>>,
          TError,
          Awaited<ReturnType<typeof findByStatus1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus1<TData = Awaited<ReturnType<typeof findByStatus1>>, TError = unknown>(
 status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindByStatus1<TData = Awaited<ReturnType<typeof findByStatus1>>, TError = unknown>(
 status: 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindByStatus1QueryOptions(status,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



