/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface ObjectId {
  timestamp?: number;
  date?: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  ADMIN: 'ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  EMPLOYEE: 'EMPLOYEE',
  CLIENT: 'CLIENT',
} as const;

export interface User {
  id?: ObjectId;
  email?: string;
  password?: string;
  role?: UserRole;
  refId?: ObjectId;
}

export type RoomStatus = typeof RoomStatus[keyof typeof RoomStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomStatus = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
} as const;

export interface Room {
  id?: ObjectId;
  number?: string;
  type?: string;
  description?: string;
  capacity?: number;
  dailyRate?: number;
  status?: RoomStatus;
}

export interface Product {
  id?: ObjectId;
  name?: string;
  category?: string;
  price?: number;
  active?: boolean;
}

export interface Employee {
  id?: ObjectId;
  name?: string;
  cpf?: string;
  phone?: string;
}

export interface Client {
  id?: ObjectId;
  name?: string;
  cpf?: string;
  email?: string;
  phone?: string;
  address?: string;
}

export interface Consumption {
  productId?: ObjectId;
  productName?: string;
  quantity?: number;
  unitPrice?: number;
  registeredAt?: string;
}

export type StayStatus = typeof StayStatus[keyof typeof StayStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StayStatus = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
} as const;

export interface Stay {
  id?: ObjectId;
  bookingId?: ObjectId;
  checkInAt?: string;
  checkOutAt?: string;
  checkInEmployeeId?: ObjectId;
  checkOutEmployeeId?: ObjectId;
  consumptions?: Consumption[];
  totalDailies?: number;
  totalConsumptions?: number;
  grandTotal?: number;
  status?: StayStatus;
}

export type BookingStatus = typeof BookingStatus[keyof typeof BookingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  CHECKIN: 'CHECKIN',
  CHECKOUT: 'CHECKOUT',
} as const;

export interface Booking {
  id?: ObjectId;
  roomId?: ObjectId;
  guests?: Guest[];
  checkInDate?: string;
  checkOutDate?: string;
  dailyRate?: number;
  advancePayment?: number;
  status?: BookingStatus;
  cancellation?: Cancellation;
  createdAt?: string;
}

export interface Cancellation {
  cancelledAt?: string;
  reason?: string;
  refundAmount?: number;
}

export interface Guest {
  clientId?: ObjectId;
  holder?: boolean;
}

export type AddConsumptionBody = {[key: string]: string};

export type CheckOutBody = {[key: string]: string};

export type CheckInBody = {[key: string]: string};

export type CancelBody = {[key: string]: string};

