/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Client
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const findById4 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Client>(
      {url: `/clients/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById4QueryKey = (id?: string,) => {
    return [
    `/clients/${id}`
    ] as const;
    }

    
export const getFindById4QueryOptions = <TData = Awaited<ReturnType<typeof findById4>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById4QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById4>>> = ({ signal }) => findById4(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById4QueryResult = NonNullable<Awaited<ReturnType<typeof findById4>>>
export type FindById4QueryError = unknown


export function useFindById4<TData = Awaited<ReturnType<typeof findById4>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById4>>,
          TError,
          Awaited<ReturnType<typeof findById4>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById4<TData = Awaited<ReturnType<typeof findById4>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById4>>,
          TError,
          Awaited<ReturnType<typeof findById4>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById4<TData = Awaited<ReturnType<typeof findById4>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById4<TData = Awaited<ReturnType<typeof findById4>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById4>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById4QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const update4 = (
    id: string,
    client: Client,
 ) => {
      
      
      return customInstance<Client>(
      {url: `/clients/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: client
    },
      );
    }
  


export const getUpdate4MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update4>>, TError,{id: string;data: Client}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof update4>>, TError,{id: string;data: Client}, TContext> => {

const mutationKey = ['update4'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update4>>, {id: string;data: Client}> = (props) => {
          const {id,data} = props ?? {};

          return  update4(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Update4MutationResult = NonNullable<Awaited<ReturnType<typeof update4>>>
    export type Update4MutationBody = Client
    export type Update4MutationError = unknown

    export const useUpdate4 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update4>>, TError,{id: string;data: Client}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof update4>>,
        TError,
        {id: string;data: Client},
        TContext
      > => {

      const mutationOptions = getUpdate4MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const delete4 = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/clients/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDelete4MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete4>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof delete4>>, TError,{id: string}, TContext> => {

const mutationKey = ['delete4'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete4>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  delete4(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete4MutationResult = NonNullable<Awaited<ReturnType<typeof delete4>>>
    
    export type Delete4MutationError = unknown

    export const useDelete4 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete4>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete4>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDelete4MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAll4 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Client[]>(
      {url: `/clients`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll4QueryKey = () => {
    return [
    `/clients`
    ] as const;
    }

    
export const getFindAll4QueryOptions = <TData = Awaited<ReturnType<typeof findAll4>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll4QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll4>>> = ({ signal }) => findAll4(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll4QueryResult = NonNullable<Awaited<ReturnType<typeof findAll4>>>
export type FindAll4QueryError = unknown


export function useFindAll4<TData = Awaited<ReturnType<typeof findAll4>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll4>>,
          TError,
          Awaited<ReturnType<typeof findAll4>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll4<TData = Awaited<ReturnType<typeof findAll4>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll4>>,
          TError,
          Awaited<ReturnType<typeof findAll4>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll4<TData = Awaited<ReturnType<typeof findAll4>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll4<TData = Awaited<ReturnType<typeof findAll4>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll4>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll4QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const create4 = (
    client: Client,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Client>(
      {url: `/clients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: client, signal
    },
      );
    }
  


export const getCreate4MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create4>>, TError,{data: Client}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create4>>, TError,{data: Client}, TContext> => {

const mutationKey = ['create4'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create4>>, {data: Client}> = (props) => {
          const {data} = props ?? {};

          return  create4(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create4MutationResult = NonNullable<Awaited<ReturnType<typeof create4>>>
    export type Create4MutationBody = Client
    export type Create4MutationError = unknown

    export const useCreate4 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create4>>, TError,{data: Client}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create4>>,
        TError,
        {data: Client},
        TContext
      > => {

      const mutationOptions = getCreate4MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    