/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Employee
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const findById3 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Employee>(
      {url: `/employees/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById3QueryKey = (id?: string,) => {
    return [
    `/employees/${id}`
    ] as const;
    }

    
export const getFindById3QueryOptions = <TData = Awaited<ReturnType<typeof findById3>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById3QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById3>>> = ({ signal }) => findById3(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById3QueryResult = NonNullable<Awaited<ReturnType<typeof findById3>>>
export type FindById3QueryError = unknown


export function useFindById3<TData = Awaited<ReturnType<typeof findById3>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById3>>,
          TError,
          Awaited<ReturnType<typeof findById3>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById3<TData = Awaited<ReturnType<typeof findById3>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById3>>,
          TError,
          Awaited<ReturnType<typeof findById3>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById3<TData = Awaited<ReturnType<typeof findById3>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById3<TData = Awaited<ReturnType<typeof findById3>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById3>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById3QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const update3 = (
    id: string,
    employee: Employee,
 ) => {
      
      
      return customInstance<Employee>(
      {url: `/employees/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: employee
    },
      );
    }
  


export const getUpdate3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update3>>, TError,{id: string;data: Employee}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof update3>>, TError,{id: string;data: Employee}, TContext> => {

const mutationKey = ['update3'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof update3>>, {id: string;data: Employee}> = (props) => {
          const {id,data} = props ?? {};

          return  update3(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Update3MutationResult = NonNullable<Awaited<ReturnType<typeof update3>>>
    export type Update3MutationBody = Employee
    export type Update3MutationError = unknown

    export const useUpdate3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof update3>>, TError,{id: string;data: Employee}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof update3>>,
        TError,
        {id: string;data: Employee},
        TContext
      > => {

      const mutationOptions = getUpdate3MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const delete3 = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/employees/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDelete3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete3>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof delete3>>, TError,{id: string}, TContext> => {

const mutationKey = ['delete3'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof delete3>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  delete3(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Delete3MutationResult = NonNullable<Awaited<ReturnType<typeof delete3>>>
    
    export type Delete3MutationError = unknown

    export const useDelete3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof delete3>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof delete3>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDelete3MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAll3 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Employee[]>(
      {url: `/employees`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll3QueryKey = () => {
    return [
    `/employees`
    ] as const;
    }

    
export const getFindAll3QueryOptions = <TData = Awaited<ReturnType<typeof findAll3>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll3QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll3>>> = ({ signal }) => findAll3(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll3QueryResult = NonNullable<Awaited<ReturnType<typeof findAll3>>>
export type FindAll3QueryError = unknown


export function useFindAll3<TData = Awaited<ReturnType<typeof findAll3>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll3>>,
          TError,
          Awaited<ReturnType<typeof findAll3>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll3<TData = Awaited<ReturnType<typeof findAll3>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll3>>,
          TError,
          Awaited<ReturnType<typeof findAll3>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll3<TData = Awaited<ReturnType<typeof findAll3>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll3<TData = Awaited<ReturnType<typeof findAll3>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll3>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll3QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const create3 = (
    employee: Employee,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Employee>(
      {url: `/employees`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: employee, signal
    },
      );
    }
  


export const getCreate3MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create3>>, TError,{data: Employee}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof create3>>, TError,{data: Employee}, TContext> => {

const mutationKey = ['create3'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create3>>, {data: Employee}> = (props) => {
          const {data} = props ?? {};

          return  create3(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type Create3MutationResult = NonNullable<Awaited<ReturnType<typeof create3>>>
    export type Create3MutationBody = Employee
    export type Create3MutationError = unknown

    export const useCreate3 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create3>>, TError,{data: Employee}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create3>>,
        TError,
        {data: Employee},
        TContext
      > => {

      const mutationOptions = getCreate3MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    