spring.application.name=theBestHotel

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/thebesthotel

# JWT
jwt.secret=TheBestHotelSecretKey2026ChangeInProductionMustBeAtLeast256BitsLong
jwt.expiration=86400000
