/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddConsumptionBody,
  CheckInBody,
  CheckOutBody,
  Stay
} from '../openAPIDefinition.schemas';

import { customInstance } from '../../lib/axios';




export const addConsumption = (
    id: string,
    addConsumptionBody: AddConsumptionBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay>(
      {url: `/stays/${id}/consumption`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addConsumptionBody, signal
    },
      );
    }
  


export const getAddConsumptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addConsumption>>, TError,{id: string;data: AddConsumptionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addConsumption>>, TError,{id: string;data: AddConsumptionBody}, TContext> => {

const mutationKey = ['addConsumption'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addConsumption>>, {id: string;data: AddConsumptionBody}> = (props) => {
          const {id,data} = props ?? {};

          return  addConsumption(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddConsumptionMutationResult = NonNullable<Awaited<ReturnType<typeof addConsumption>>>
    export type AddConsumptionMutationBody = AddConsumptionBody
    export type AddConsumptionMutationError = unknown

    export const useAddConsumption = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addConsumption>>, TError,{id: string;data: AddConsumptionBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addConsumption>>,
        TError,
        {id: string;data: AddConsumptionBody},
        TContext
      > => {

      const mutationOptions = getAddConsumptionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const checkOut = (
    id: string,
    checkOutBody: CheckOutBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay>(
      {url: `/stays/${id}/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkOutBody, signal
    },
      );
    }
  


export const getCheckOutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,{id: string;data: CheckOutBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,{id: string;data: CheckOutBody}, TContext> => {

const mutationKey = ['checkOut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkOut>>, {id: string;data: CheckOutBody}> = (props) => {
          const {id,data} = props ?? {};

          return  checkOut(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CheckOutMutationResult = NonNullable<Awaited<ReturnType<typeof checkOut>>>
    export type CheckOutMutationBody = CheckOutBody
    export type CheckOutMutationError = unknown

    export const useCheckOut = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkOut>>, TError,{id: string;data: CheckOutBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkOut>>,
        TError,
        {id: string;data: CheckOutBody},
        TContext
      > => {

      const mutationOptions = getCheckOutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const checkIn = (
    checkInBody: CheckInBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay>(
      {url: `/stays/checkin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkInBody, signal
    },
      );
    }
  


export const getCheckInMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,{data: CheckInBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,{data: CheckInBody}, TContext> => {

const mutationKey = ['checkIn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof checkIn>>, {data: CheckInBody}> = (props) => {
          const {data} = props ?? {};

          return  checkIn(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CheckInMutationResult = NonNullable<Awaited<ReturnType<typeof checkIn>>>
    export type CheckInMutationBody = CheckInBody
    export type CheckInMutationError = unknown

    export const useCheckIn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof checkIn>>, TError,{data: CheckInBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof checkIn>>,
        TError,
        {data: CheckInBody},
        TContext
      > => {

      const mutationOptions = getCheckInMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const findAll6 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay[]>(
      {url: `/stays`, method: 'GET', signal
    },
      );
    }
  



export const getFindAll6QueryKey = () => {
    return [
    `/stays`
    ] as const;
    }

    
export const getFindAll6QueryOptions = <TData = Awaited<ReturnType<typeof findAll6>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAll6QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll6>>> = ({ signal }) => findAll6(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAll6QueryResult = NonNullable<Awaited<ReturnType<typeof findAll6>>>
export type FindAll6QueryError = unknown


export function useFindAll6<TData = Awaited<ReturnType<typeof findAll6>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll6>>,
          TError,
          Awaited<ReturnType<typeof findAll6>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll6<TData = Awaited<ReturnType<typeof findAll6>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAll6>>,
          TError,
          Awaited<ReturnType<typeof findAll6>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAll6<TData = Awaited<ReturnType<typeof findAll6>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAll6<TData = Awaited<ReturnType<typeof findAll6>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAll6>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAll6QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const findById5 = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay>(
      {url: `/stays/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getFindById5QueryKey = (id?: string,) => {
    return [
    `/stays/${id}`
    ] as const;
    }

    
export const getFindById5QueryOptions = <TData = Awaited<ReturnType<typeof findById5>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindById5QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findById5>>> = ({ signal }) => findById5(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindById5QueryResult = NonNullable<Awaited<ReturnType<typeof findById5>>>
export type FindById5QueryError = unknown


export function useFindById5<TData = Awaited<ReturnType<typeof findById5>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById5>>,
          TError,
          Awaited<ReturnType<typeof findById5>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById5<TData = Awaited<ReturnType<typeof findById5>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findById5>>,
          TError,
          Awaited<ReturnType<typeof findById5>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindById5<TData = Awaited<ReturnType<typeof findById5>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindById5<TData = Awaited<ReturnType<typeof findById5>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findById5>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindById5QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const findByStatus = (
    status: 'ACTIVE' | 'CLOSED',
 signal?: AbortSignal
) => {
      
      
      return customInstance<Stay[]>(
      {url: `/stays/status/${status}`, method: 'GET', signal
    },
      );
    }
  



export const getFindByStatusQueryKey = (status?: 'ACTIVE' | 'CLOSED',) => {
    return [
    `/stays/status/${status}`
    ] as const;
    }

    
export const getFindByStatusQueryOptions = <TData = Awaited<ReturnType<typeof findByStatus>>, TError = unknown>(status: 'ACTIVE' | 'CLOSED', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindByStatusQueryKey(status);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findByStatus>>> = ({ signal }) => findByStatus(status, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(status), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindByStatusQueryResult = NonNullable<Awaited<ReturnType<typeof findByStatus>>>
export type FindByStatusQueryError = unknown


export function useFindByStatus<TData = Awaited<ReturnType<typeof findByStatus>>, TError = unknown>(
 status: 'ACTIVE' | 'CLOSED', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus>>,
          TError,
          Awaited<ReturnType<typeof findByStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus<TData = Awaited<ReturnType<typeof findByStatus>>, TError = unknown>(
 status: 'ACTIVE' | 'CLOSED', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findByStatus>>,
          TError,
          Awaited<ReturnType<typeof findByStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindByStatus<TData = Awaited<ReturnType<typeof findByStatus>>, TError = unknown>(
 status: 'ACTIVE' | 'CLOSED', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindByStatus<TData = Awaited<ReturnType<typeof findByStatus>>, TError = unknown>(
 status: 'ACTIVE' | 'CLOSED', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findByStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindByStatusQueryOptions(status,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



